/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oop.project;

import java.util.List;
import java.util.Vector;

public class App
{
    public String getGreeting()
    {
        return "Hello world.";
    }

    public static void main(String[] args)
    {
        System.out.println(new App().getGreeting());
    }
}
